name: Build and Release

on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  apk:
    name: Generate APK
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Intialising Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.7'
          channel: stable

      - run: flutter --version
      - run: flutter pub get

      - name: Build APK
        run: flutter build apk --debug --split-per-abi

      - name: Uploading Artifact | arm64 APK
        uses: actions/upload-artifact@v1
        with:
          name: split-apk
          path: "build/app/outputs/apk/debug/app-arm64-v8a-debug.apk"

      - name: Uploading Artifact | armeabi APK
        uses: actions/upload-artifact@v1
        with:
          name: split-apk
          path: "build/app/outputs/apk/debug/app-armeabi-v7a-debug.apk"

      - name: Uploading Artifact | x86_64 APK
        uses: actions/upload-artifact@v1
        with:
          name: split-apk
          path: "build/app/outputs/apk/debug/app-x86_64-debug.apk"

  release:
    name: Release APK
    needs: apk
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v1
        with:
          name: split-apk
          path: apk

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: ${{ github.event.repository.name }} v${{ github.run_number }}

      - name: Upload APK (arm64-v8a)
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: apk/app-arm64-v8a-debug.apk
          asset_name: ${{ github.event.repository.name }}-arm64.apk
          asset_content_type: application/zip

      - name: Upload APK (armeabi-v7a)
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: apk/app-armeabi-v7a-debug.apk
          asset_name: ${{ github.event.repository.name }}-armeabi.apk
          asset_content_type: application/zip

      - name: Upload APK (x86_64)
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: apk/app-armeabi-v7a-debug.apk
          asset_name: ${{ github.event.repository.name }}-x86_64.apk
          asset_content_type: application/zip
